### ISSUE TITLE
Cannot open transciption file (.xsc) file from file manager.

### ISSUE THREAD

**Issue by ptrv** [flathub/com.seventhstring.Transcribe#2]
Opening a transcription file (.xsc) file from file manager (nautilus) only starts application because `transcribe-wrapper` does not pass the file path to the application, due to missing argument.

**Comment by MichaHoffmann** [comment]
Hey @ptrv, 

good catch, would you mind submitting a patch? Otherwise i can look into it on the weekend.

**Comment by ptrv** [comment]
Hi @MichaHoffmann ,

I'm not able to submit a patch at the moment. Please have a look when you can. Thanks!

**Comment by MichaHoffmann** [comment]
Hey @ptrv,

do you mind testing out the test build just to verify? It works for me locally.

**Comment by ptrv** [comment]
I've tested the build. It works for me too.

**Comment by MichaHoffmann** [comment]
Ill close this then after the PR is merged!
