### ISSUE TITLE
New version 9.20 available

### ISSUE THREAD

**Issue by ptrv** [flathub/com.seventhstring.Transcribe#5]
New version was released: 9.20

https://www.seventhstring.com/xscribe/download_linux.html

**Comment by MichaHoffmann** [comment]
Thanks, ill bump it tomorrow!

**Comment by MichaHoffmann** [comment]
Installed the test build locally, looked good

**Comment by MichaHoffmann** [comment]
after `flatpak update com.seventhstring.Transcribe` it now shows the new version too
