### ISSUE TITLE
mime filetype is not exported

### ISSUE THREAD

**Issue by ptrv** [flathub/com.seventhstring.Transcribe#6]
I noticed that the Transcribe filetype is not exported and `.xsc` files are not associated with Transcribe.

Checking the mime type of an `.xsc` with `file --mime-type <some_file>.xsc` returns `text/plain`

**Comment by MichaHoffmann** [comment]
good catch! Im not sure how to export the mimetype from the flatpak though.

**Comment by ptrv** [comment]
I'm also not sure. The transcribe installer installs a mime file and lands in `/var/lib/flatpak/app/com.seventhstring.Transcribe/current/active/files/share/mime`. I think it has to be copied into `/var/lib/flatpak/app/com.seventhstring.Transcribe/current/active/export/share/mime` somehow. And ultimately the mime definition has to be in `/var/lib/flatpak/exports/share/mime`. I think. I'm not very familiar with flatpak packaging. I just observed the paths in other packages that have a mime type.

**Comment by MichaHoffmann** [comment]
Can you link me another package? That would be very helpful; i imagine that we can eventually just adapt the included mimetype definition and install it at the proper location.

**Comment by MichaHoffmann** [comment]
It would be cool if flatpak would support `rename-mime` in addition to `rename-icon` and `rename-desktop-file`

**Comment by ptrv** [comment]
I think renaming `/app/share/mime/packages/seventhstring-transcribe.xml` into `/app/share/mime/packages/com.seventhstring.Transcribe.xml` in post-install after the `desktop-file-edit` does the trick.

**Comment by MichaHoffmann** [comment]
Have you tried? If so could you open a PR? Otherwise ill see if i can do something tomorrow!

**Comment by ptrv** [comment]
The github search in flathub shows some results. Looks like many packages had the same problem.

https://github.com/search?q=org%3Aflathub+rename+mime&type=commits

**Comment by ptrv** [comment]
It looks like the icon name in the original .xml file (/app/share/mime/packages/seventhstring-transcribe.xml) needs to be renamed too, to match the app ID

**Comment by ptrv** [comment]
Commit in LMMS package https://github.com/flathub/io.lmms.LMMS/commit/a636bf1c85f437449a98e1f524e31498676d375d

**Comment by ptrv** [comment]
This works:
Add to transcribe module's post-install after `desktop-file-edit` line
```
- mv /app/share/mime/packages/{seventhstring-transcribe.xml,${FLATPAK_ID}.xml}
- sed -i "s/icon name=\"seventhstring-transcribe\"/icon name=\"${FLATPAK_ID}\"/g" /app/share/mime/packages/${FLATPAK_ID}.xml
```

**Comment by MichaHoffmann** [comment]
Thanks ill test it out tomorrow and create a PR then!

**Comment by MichaHoffmann** [comment]
Ok created the PR; let me install the test build; locally it looked as though the mime type file was installed in the correct location though

**Comment by MichaHoffmann** [comment]
Change looked good after installing the test flatpak. I'll push the build once the package has been built.

**Comment by MichaHoffmann** [comment]
Thansk @ptrv !

**Comment by ptrv** [comment]
Thanks @MichaHoffmann for your work on the package!
